version: '3.4'

services:
  dotnetcore.api.template:
    environment:
      - ASPNETCORE_ENVIRONMENT=local
      #- ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_URLS = http://+:80
     # - ASPNETCORE_HTTPS_PORT=44320
    ports:
      - "50447:80"
     # - "44320:443"
    volumes:
     # - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro